name: Pull Requests

on:
  pull_request:
    branches: [ master, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - run: npm i -g pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
      - run: pnpm build
